export const CITIES = [
  {
    rank: 1,
    internetSpeed: 13,
    city: "Bangkok",
    country: "Thailand",
    img: "https://nomadlist.com/assets/img/places/bangkok-thailand.jpg?1674345655",
    cost: 8,
    overall: 8,
    internet: 8,
    fun: 3,
    safety: 8,
  },
  {
    rank: 2,
    internetSpeed: 9,
    city: "Buenos Aires",
    country: "Argentina",
    img: "https://nomadlist.com/assets/img/places/buenos-aires-argentina.jpg?1659830443",
    cost: 7,
    overall: 9,
    internet: 9,
    fun: 9,
    safety: 8,
  },
  {
    rank: 3,
    internetSpeed: 13,
    city: "Lisbon",
    country: "Portugal",
    img: "https://nomadlist.com/assets/img/places/lisbon-portugal.jpg?1674345656",
    cost: 5,
    overall: 6,
    internet: 7,
    fun: 7,
    safety: 7,
  },
  {
    rank: 4,
    internetSpeed: 8,
    city: "Canggu",
    country: "Bali",
    img: "https://nomadlist.com/assets/img/places/canggu-bali-indonesia.jpg?1673049698",
    cost: 8,
    overall: 8,
    internet: 8,
    fun: 9,
    safety: 9,
  },
  {
    rank: 5,
    internetSpeed: 13,
    city: "Chaing Mai",
    country: "Thailand",
    img: "https://nomadlist.com/assets/img/places/chiang-mai-thailand.jpg?1674691255",
    cost: 4,
    overall: 3,
    internet: 8,
    fun: 2,
    safety: 5,
  },
  {
    rank: 6,
    internetSpeed: 33,
    city: "Mexico City",
    country: "Mexico",
    img: "https://nomadlist.com/assets/img/places/mexico-city-mexico.jpg?1674864062",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 7,
    internetSpeed: 21,
    city: "Maderia",
    country: "Portugal",
    img: "https://nomadlist.com/assets/img/places/madeira-portugal.jpg?1672704064",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 8,
    internetSpeed: 19,
    city: "Grah Canaria, Canary Islands",
    country: "Spain",
    img: "https://nomadlist.com/assets/img/places/gran-canaria-canary-islands-spain.jpg?1672876890",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 9,
    internetSpeed: 11,
    city: "Medellin",
    country: "Colombia",
    img: "https://nomadlist.com/assets/img/places/medellin-colombia.jpg?1674691262",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 10,
    internetSpeed: 14,
    city: "Tmisoara",
    country: "Romania",
    img: "https://nomadlist.com/assets/img/places/timisoara-romania.jpg?1674691264",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 11,
    internetSpeed: 23,
    city: "Penang",
    country: "Malaysia",
    img: "https://nomadlist.com/assets/img/places/penang-malaysia.jpg?1674604876",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
  {
    rank: 12,
    internetSpeed: 33,
    city: "Bengaluru",
    country: "India",
    img: "https://nomadlist.com/assets/img/places/bengaluru-india.jpg?1662163246",
    cost: 4,
    overall: 6,
    internet: 8,
    fun: 6,
    safety: 8,
  },
];

export const PUBLICATION_CONSTANT = [
  {
    key: 1,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/nyt-wide.png?6",
  },
  {
    key: 2,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/ft.png?6",
  },
  {
    key: 3,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/bbc.png?6",
  },
  {
    key: 4,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/cnn.png?6",
  },
  {
    key: 5,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/usa-today.png?6",
  },
  {
    key: 6,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/cnbc.png?6",
  },
  {
    key: 7,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/guardian.png?6",
  },
  {
    key: 8,
    img: "https://nomadlist.com/cdn-cgi/image/format=auto,fit=cover,height=60,quality=25/https://nomadlist.com/assets/featured/politico.png?6",
  },
];
